# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - devel

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git branch master
    git checkout master
    date > timestamp.log
    git config --global user.email "noreply@jaapbrasser.com"
    git config --global user.name "jaapbrasser"
    git status
    git branch
    git add *
    git commit -m "Updating based on merge to master $(date)"
    git push -u origin master