trigger:
  branches:
    include:
    - master
    - devel
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
- task: ShellScript@2
  inputs:
    scriptPath: ./gitmerge.sh